### ISSUE TITLE
Option to change units

### ISSUE THREAD

**Issue by tmjo** [toreamun/amshan-homeassistant#40]
Hi! Just started using this integration together with local Tibber Pulse through MQTT, seems to be working great! Thanks for your awesome work here!

Would you consider adding an option to choose kW and kVAR instead of W and VAR as units?

Thanks again!

**Comment by toreamun** [comment]
My approach has been to use the native unit of measurement since this concept was introduces in HASS. My hope was that the introduction of native unit in HASS sensor was the first step in making the display unit more configurable in HASS. You can currently use a [template sensor](https://www.home-assistant.io/integrations/template/#trigger-based-template-binary-sensors-buttons-numbers-selects-and-sensors) to do the conversion into a new entity.

**Comment by tmjo** [comment]
Sure, I know and thanks for your reply. I agree and I understand your point of view. I'm also hoping that there will be a native way of changing units, and it seems like it is finding it's way. Started with weather units, and more and more seem to follow. Let's hope it finds it way to power- and energy sensors as well! Ref [here](https://developers.home-assistant.io/blog/2022/09/28/new_sensor_device_classes).

**Comment by tmjo** [comment]
Closing issue as we hope for native support of unit conversion.
